services:
  traefik:
    image: traefik:v3.6
    container_name: traefik_3
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy_traefik
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Монтируем папку live. ВАЖНО: используйте fullchain.pem и privkey.pem
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./dynamic:/dynamic:ro

    command:
      - "--api.dashboard=true"
      # Точки входа
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.websecure.address=:443"
      # Включаем использование сертификатов из файлов
      - "--providers.file.directory=/dynamic"
      - "--providers.file.watch=true"
      # Docker провайдер
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=proxy_traefik"

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`dashboard.xmilitary.online`)"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.tls=true" # Traefik сам найдет подходящий сертификат в /certs
      - "traefik.http.middlewares.test-auth.basicauth.users=test:$$2a$$12$$g6eSSC6Y9A2mwYdQ7roaQOYLfy5QKBe7t/uaQvS6bMPzxNRFw24um"
      - "traefik.http.routers.dashboard.middlewares=test-auth"

  whoami:
    image: traefik/whoami
    container_name: whoami_3
    networks:
      - proxy_traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`xmilitary.online`) && Path(`/whoami`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls=true"

networks:
  proxy_traefik:
    external: true