services:
  telegram-bot:
    build:
      context: .
      dockerfile: ./bot/Dockerfile.bot
    container_name: telegram-bot
    restart: no
#    ports:
#      - "8080:8080"
    volumes:
      - ./bot/bot.py:/app/bot.py
      - ./bot/images:/app/images
    environment:
      - WEB_SERVER_URL=https://web.xmilitary.online
      - API_TOKEN=1873920038:AAGbA5l5Uv0qqLRxYrcs1iShTaZ0MBH7eM4
      - BOT_HOST=0.0.0.0
      - BOT_PORT=8080
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tg_bot.rule=Host(`tgbot.xmilitary.online`)"
      - "traefik.http.routers.tg_bot.entrypoints=websecure"
      - "traefik.http.routers.tg_bot.tls=true"
      - "traefik.http.services.tg_bot.loadbalancer.server.port=8080"
    networks:
      - proxy_traefik

networks:
  proxy_traefik:
    external: true