services:
  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: no
    volumes:
      - ./bot/bot.py:/app/bot.py
      - ./bot/images:/app/images
    environment:
      - BOT_MODE=polling
      - BOT_TOKEN=1873920038:AAGbA5l5Uv0qqLRxYrcs1iShTaZ0MBH7eM4
      - WEBHOOK_URL=https://tgbot.xmilitary.online/telegram/webhook
      - WEB_API_URL=http://host.docker.internal:3000
    ports:
      - "8001:8001"
    networks:
      - proxy

networks:
  proxy:
    external: true
