FROM nginx:alpine

# Удаляем дефолтную конфигурацию
RUN rm /etc/nginx/conf.d/default.conf

# Копируем нашу конфигурацию
COPY nginx.conf /etc/nginx/nginx.conf

# Копируем SSL сертификаты
COPY ssl /etc/nginx/ssl

# Создаем директорию для статики
RUN mkdir -p /usr/share/nginx/html

EXPOSE 80 443