services:
  web-server:
    build:
      context: .
      dockerfile: ./web/Dockerfile.web
    restart: no
    volumes:
      - ./web/index.html:/app/index.html
      - ./web/package.json:/app/package.json
      - ./web/server.js:/app/server.js
      - ./web/scripts.js:/app/scripts.js
      - ./web/images:/app/images
    environment:
      - TELEGRAM_BOT_URL=https://tgbot.xmilitary.online
      - NODE_ENV=production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web_interface.rule=Host(`web.xmilitary.online`)"
      - "traefik.http.routers.web_interface.service=web_interface"
      - "traefik.http.routers.web_interface.entrypoints=websecure"
      - "traefik.http.routers.web_interface.tls=true"
      - "traefik.http.services.web_interface.loadbalancer.server.port=3000"
    networks:
      - proxy_traefik

networks:
  proxy_traefik:
    external: true
